// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFoTn9u2FRwkGWBciVDjZ0YQGn5UyvdHo',
    appId: '1:377654590603:web:17fb0c021e5bbe2436e88e',
    messagingSenderId: '377654590603',
    projectId: 'chat-d60f5',
    authDomain: 'chat-d60f5.firebaseapp.com',
    storageBucket: 'chat-d60f5.appspot.com',
    measurementId: 'G-HM6F3ELJ77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAks-2BY0oThHsHSm0pSsMpCjZqcnsEwxQ',
    appId: '1:377654590603:android:f99c8b796dde6d4d36e88e',
    messagingSenderId: '377654590603',
    projectId: 'chat-d60f5',
    storageBucket: 'chat-d60f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlZ-7BVG3jPGYBsiL7N7_53Rf8bakR-vk',
    appId: '1:377654590603:ios:a9245b9eb3823b1736e88e',
    messagingSenderId: '377654590603',
    projectId: 'chat-d60f5',
    storageBucket: 'chat-d60f5.appspot.com',
    iosBundleId: 'com.example.amricanDreeamOsh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlZ-7BVG3jPGYBsiL7N7_53Rf8bakR-vk',
    appId: '1:377654590603:ios:a9245b9eb3823b1736e88e',
    messagingSenderId: '377654590603',
    projectId: 'chat-d60f5',
    storageBucket: 'chat-d60f5.appspot.com',
    iosBundleId: 'com.example.amricanDreeamOsh',
  );
}
